#!/usr/bin/env python3
"""Count which GitHub MCP tools were actually called, and roll them up to toolsets.

This exists to answer one question with evidence instead of taste: the GitHub
MCP server offers 22 toolsets and 89 tools, every enabled tool costs context in
every session, and `--toolsets` is the only lever. Guessing the list is how you
end up carrying `stargazers` for a year and discovering, the first time a CI
skill is written, that `actions` was never enabled.

So: run everything for a fortnight, then run this. It reads Claude Code session
transcripts, counts `mcp__github__*` tool calls, maps each to the toolset that
supplies it, and prints the `--toolsets` line the observed calls justify along
with what it saves. See docs/github-mcp.md for the standing decision and the
reasoning behind it.

It also counts `gh` invocations, because the demotion of `gh` to a laptop-only
escape hatch is a claim with the same shape: residual `gh` use is the list of
things the MCP did not do, and it is worth reading rather than assuming.

Usage:

    python3 scripts/github-mcp-usage.py                    # all transcripts
    python3 scripts/github-mcp-usage.py --since 2026-09-06 # the fortnight
    python3 scripts/github-mcp-usage.py --projects DIR     # a non-default root

No third-party imports, for the same reason as check-manifests.py: this runs
from a Makefile on a laptop, and a dependency install is a place for two runs
to differ.
"""

from __future__ import annotations

import argparse
import json
import re
import shlex
import sys
from collections import Counter
from pathlib import Path

# Tool -> (toolsets that supply it, characters of its JSON definition).
#
# Generated by launching `github-mcp-server stdio` once per toolset and taking
# `tools/list` from each — the server's own answer, not the README's table,
# which is generated separately and can lag. Provenance:
# github/github-mcp-server v1.12.0 (9205304, 2026-09-03), measured 2026-09-06.
#
# Sizes are compact JSON (no whitespace) of the full tool definition, name and
# input schema included. They are what the context actually pays. Regenerate
# by rerunning the probe; a tool absent from this table is reported rather
# than silently dropped, so drift shows up as output instead of as a wrong
# recommendation.
TOOLS: dict[str, tuple[str, int]] = {
    "actions_get": ("actions", 2664),
    "actions_list": ("actions", 4108),
    "actions_run_trigger": ("actions", 2615),
    "add_comment_to_pending_review": ("pull_requests", 3519),
    "add_issue_comment": ("issues", 3279),
    "add_reply_to_pull_request_comment": ("pull_requests", 3101),
    "assign_copilot_to_issue": ("copilot", 3203),
    "assign_copilot_to_issue_with_intent": ("copilot_issue_intents", 4030),
    "create_branch": ("repos", 1697),
    "create_gist": ("gists", 3119),
    "create_or_update_file": ("repos", 2896),
    "create_pull_request": ("pull_requests", 2819),
    "create_repository": ("repos", 1877),
    "create_repository_ruleset": ("governance", 5420),
    "custom_properties_read": ("governance", 3392),
    "custom_properties_write": ("governance", 6162),
    "delete_file": ("repos", 1805),
    "discussion_comment_write": ("discussions", 3075),
    "dismiss_notification": ("notifications", 2041),
    "fork_repository": ("repos", 2341),
    "get_code_quality_finding": ("code_quality", 1914),
    "get_code_scanning_alert": ("code_security", 2717),
    "get_commit": ("repos", 2265),
    "get_dependabot_alert": ("dependabot", 1720),
    "get_discussion": ("discussions", 1768),
    "get_discussion_comments": ("discussions", 2225),
    "get_file_contents": ("repos", 2368),
    "get_gist": ("gists", 2865),
    "get_global_security_advisory": ("security_advisories", 2202),
    "get_job_logs": ("actions", 2606),
    "get_label": ("issues,labels", 2441),
    "get_latest_release": ("repos", 1548),
    "get_me": ("context", 1955),
    "get_notification_details": ("notifications", 2077),
    "get_release_by_tag": ("repos", 1643),
    "get_repository_tree": ("git", 2717),
    "get_secret_scanning_alert": ("secret_protection", 2523),
    "get_tag": ("repos", 1603),
    "get_team_members": ("context", 2088),
    "get_teams": ("context", 2000),
    "issue_read": ("issues", 3396),
    "issue_write": ("issues", 5671),
    "label_write": ("labels", 2358),
    "list_branches": ("repos", 1736),
    "list_code_scanning_alerts": ("code_security", 3315),
    "list_commits": ("repos", 2875),
    "list_dependabot_alerts": ("dependabot", 2132),
    "list_discussion_categories": ("discussions", 1831),
    "list_discussions": ("discussions", 2391),
    "list_gists": ("gists", 3151),
    "list_global_security_advisories": ("security_advisories", 3382),
    "list_issue_fields": ("issues", 2766),
    "list_issue_types": ("issues", 2597),
    "list_issues": ("issues", 4350),
    "list_label": ("labels", 1783),
    "list_notifications": ("notifications", 3472),
    "list_org_repository_security_advisories": ("security_advisories", 2506),
    "list_pull_requests": ("pull_requests", 3566),
    "list_releases": ("repos", 2116),
    "list_repository_collaborators": ("repos", 2233),
    "list_repository_security_advisories": ("security_advisories", 2626),
    "list_secret_scanning_alerts": ("secret_protection", 3087),
    "list_starred_repositories": ("stargazers", 2746),
    "list_tags": ("repos", 1728),
    "manage_notification_subscription": ("notifications", 2188),
    "manage_repository_notification_subscription": ("notifications", 2368),
    "mark_all_notifications_read": ("notifications", 2289),
    "merge_pull_request": ("pull_requests", 2570),
    "projects_get": ("projects", 3173),
    "projects_list": ("projects", 3358),
    "projects_write": ("projects", 8360),
    "pull_request_read": ("pull_requests", 4518),
    "pull_request_review_write": ("pull_requests", 4158),
    "push_files": ("repos", 2049),
    "repository_ruleset_read": ("governance", 5598),
    "request_copilot_review": ("copilot", 2634),
    "search_code": ("repos", 2754),
    "search_commits": ("repos", 2690),
    "search_issues": ("issues", 3961),
    "search_orgs": ("orgs", 2240),
    "search_pull_requests": ("pull_requests", 3731),
    "search_repositories": ("repos", 2347),
    "search_users": ("users", 3078),
    "star_repository": ("stargazers", 1862),
    "sub_issue_write": ("issues", 3562),
    "unstar_repository": ("stargazers", 2276),
    "update_gist": ("gists", 3084),
    "update_pull_request": ("pull_requests", 2944),
    "update_pull_request_branch": ("pull_requests", 2497),
}

# The server's own `default` — what you get by setting no toolsets at all.
# Named here so the recommendation can say whether narrowing beats doing
# nothing, which for a PR-and-issues workflow it very nearly does not.
#
# Derived by diffing `tools/list` under `default` against each toolset, not
# read off the README. Note that `get_label` belongs to both `issues` and
# `labels`, so `default` contains a `labels` tool without enabling `labels`;
# taking the toolset list from the tools alone would wrongly add it.
DEFAULT_TOOLSETS = frozenset(
    {"context", "copilot", "issues", "pull_requests", "repos", "users"}
)

MCP_PREFIX = "mcp__github__"

# A leading `VAR=value` does not stop `gh` from being in command position.
ASSIGNMENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")


def transcripts(root: Path):
    """Every session transcript under a Claude Code projects directory."""
    return sorted(root.glob("*/*.jsonl"))


def tool_uses(path: Path, since: str | None):
    """Yield (tool name, input dict) for each tool call recorded in a transcript.

    Transcript records are one JSON object per line; an assistant turn carries
    its tool calls as `tool_use` blocks in `message.content`. A malformed or
    truncated line is skipped rather than fatal — a transcript being written
    by a live session will have one.
    """
    with path.open(encoding="utf-8", errors="replace") as handle:
        for line in handle:
            try:
                record = json.loads(line)
            except (json.JSONDecodeError, ValueError):
                continue
            if not isinstance(record, dict):
                continue
            if since and (record.get("timestamp") or "") < since:
                continue
            content = (record.get("message") or {}).get("content")
            if not isinstance(content, list):
                continue
            for block in content:
                if isinstance(block, dict) and block.get("type") == "tool_use":
                    yield block.get("name") or "", block.get("input") or {}


def gh_subcommand(command: str) -> str | None:
    """The `gh` subcommand a shell command line invokes, if it invokes one.

    Deliberately shallow, and only counts `gh` in command position — at the
    start of the line or after a shell operator — so `command -v gh` and a
    `gh api` written inside a heredoc do not register as uses. Two words of
    subcommand are kept, making `gh pr create` and `gh run watch` distinct
    rows while `gh api /repos/...` collapses to `gh api`.

    This is a tally of what `gh` is still reached for, not a parser, and it is
    a live demonstration of D2's point: recognising a command in a shell
    string is guesswork, which is exactly why the hook that enforces MCP use
    matches an MCP tool name instead.
    """
    try:
        words = shlex.split(command)
    except ValueError:
        words = command.split()
    operators = {"|", "||", "&&", ";", "&", "(", ")", "{", "}", "then", "do", "else", "env"}
    subcommand = re.compile(r"^[a-z][a-z-]*$")
    for index, word in enumerate(words):
        if word != "gh":
            continue
        previous = words[index - 1] if index else None
        if previous is not None and previous not in operators and not ASSIGNMENT.match(previous):
            continue
        rest = []
        for candidate in words[index + 1 :]:
            if not subcommand.match(candidate) or len(rest) == 2:
                break
            rest.append(candidate)
        return " ".join(["gh", *rest]) if rest else "gh"
    return None


def report(mcp: Counter, gh: Counter, unknown: Counter, sessions: int) -> None:
    print(f"sessions read: {sessions}")

    print("\nGitHub MCP tools called")
    if not mcp:
        print("  (none)")
    for name, count in mcp.most_common():
        print(f"  {count:5d}  {name}  [{TOOLS[name][0]}]")

    if unknown:
        print("\nCalled but absent from this script's table — regenerate it")
        for name, count in unknown.most_common():
            print(f"  {count:5d}  {name}")

    # Resolve each called tool to one toolset. Only `get_label` has a choice
    # to make, and crediting both of its toolsets would recommend enabling
    # `labels` for a tool that `issues` already supplies — so tools with a
    # single home are settled first, and an ambiguous tool then takes a
    # toolset already required rather than adding one.
    used: set[str] = set()
    ambiguous: list[tuple[str, int]] = []
    per_toolset: Counter = Counter()
    for name, count in mcp.items():
        toolsets = TOOLS[name][0].split(",")
        if len(toolsets) == 1:
            used.add(toolsets[0])
            per_toolset[toolsets[0]] += count
        else:
            ambiguous.append((name, count))
    for name, count in ambiguous:
        toolsets = TOOLS[name][0].split(",")
        chosen = next((t for t in toolsets if t in used), toolsets[0])
        used.add(chosen)
        per_toolset[chosen] += count

    print("\nBy toolset")
    for toolset, count in per_toolset.most_common():
        print(f"  {count:5d}  {toolset}")

    everything = sum(size for _, size in TOOLS.values())
    kept = sum(
        size
        for toolsets, size in TOOLS.values()
        if used.intersection(toolsets.split(","))
    )
    default = sum(
        size
        for toolsets, size in TOOLS.values()
        if DEFAULT_TOOLSETS.intersection(toolsets.split(","))
    )

    print("\nWhat the calls justify")
    if not used:
        print("  nothing was called; the measurement has not run long enough")
    else:
        print(f"  --toolsets {','.join(sorted(used))}")
        print(f"  {len(used)} of {len({t for s, _ in TOOLS.values() for t in s.split(',')})} toolsets")
        print(f"  {kept:,} chars of tool definitions, against {everything:,} for `all`")
        print(f"  and {default:,} for the server's own `default`")
        if used <= DEFAULT_TOOLSETS and kept >= default * 0.9:
            print("  — barely under `default`; setting no toolsets at all is close enough")

    print("\n`gh` invocations (what the MCP did not do)")
    if not gh:
        print("  (none)")
    for name, count in gh.most_common():
        print(f"  {count:5d}  {name}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--projects",
        type=Path,
        default=Path.home() / ".claude" / "projects",
        help="Claude Code projects directory (default: ~/.claude/projects)",
    )
    parser.add_argument(
        "--since",
        default=None,
        help="ignore records before this ISO-8601 instant, e.g. 2026-09-06",
    )
    args = parser.parse_args()

    if not args.projects.is_dir():
        print(f"no such directory: {args.projects}", file=sys.stderr)
        return 1

    mcp: Counter = Counter()
    gh: Counter = Counter()
    unknown: Counter = Counter()
    paths = transcripts(args.projects)

    for path in paths:
        for name, payload in tool_uses(path, args.since):
            if name.startswith(MCP_PREFIX):
                tool = name[len(MCP_PREFIX) :]
                (mcp if tool in TOOLS else unknown)[tool] += 1
            elif name == "Bash":
                subcommand = gh_subcommand(str(payload.get("command") or ""))
                if subcommand:
                    gh[subcommand] += 1

    report(mcp, gh, unknown, len(paths))
    return 0


if __name__ == "__main__":
    sys.exit(main())
